<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue with GoogleContinue with Faceb_6932f6</name>
   <tag></tag>
   <elementGuidId>48d26cdc-0de7-4823-a55c-d947e1a02eaf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth__card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>968df75c-3cc4-4a68-bb80-82bc1cfb1c6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth__card-body</value>
      <webElementGuid>fde646bf-8049-4998-ab5e-c8287508d692</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In</value>
      <webElementGuid>1fc5a1db-4e60-4ca2-926f-3d6053f2f639</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]</value>
      <webElementGuid>072a78d3-e091-4e15-9187-78db92c1d6d5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]</value>
      <webElementGuid>71584a7e-dedf-4b9b-88b0-15789dcd6cf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[1]</value>
      <webElementGuid>75ec9b6b-4832-41f4-87ab-e5c924d91963</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::div[4]</value>
      <webElementGuid>c8a50454-34bb-401f-bff9-f94d707e4846</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>f7f532ad-a952-4839-9012-57c49181ad53</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In' or . = 'Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In')]</value>
      <webElementGuid>3eee062f-5072-47c1-a605-ef3a17b0073d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
