<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Account  Settings_back-arrow</name>
   <tag></tag>
   <elementGuidId>f9616f5c-5e2e-438e-b8bb-218aad5bb676</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img.back-arrow</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>37339e40-a6fa-44f1-b7b9-ddb0bbf0e68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>back-arrow</value>
      <webElementGuid>60af3667-a043-43d8-b2b3-63c60d367183</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/static/media/Back_Arrow.5eec5e27.svg</value>
      <webElementGuid>125aaa36-00b4-4bbf-b6fe-a38167239a51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Back-arrow</value>
      <webElementGuid>21ab7899-c4d7-449b-8df0-9e6c1a631b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;account--settings__main&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-6 offset-md-3&quot;]/div[@class=&quot;account card&quot;]/div[@class=&quot;account--title text-center card-header&quot;]/div[@class=&quot;d-flex justify-content-between&quot;]/img[@class=&quot;back-arrow&quot;]</value>
      <webElementGuid>eb10cff3-789d-4e97-9a8c-ad4ec5834149</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div/div/div/img</value>
      <webElementGuid>fc3a87d0-0df8-4cb6-afef-ad55ff777083</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Back-arrow']</value>
      <webElementGuid>409a50a0-edb0-4138-855c-6614e7ea4a9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>8aeded2c-6062-4005-9234-7e465deb3d80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/static/media/Back_Arrow.5eec5e27.svg' and @alt = 'Back-arrow']</value>
      <webElementGuid>4ffd686a-861d-4194-8874-19c433c28dbb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
