<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Click Here</name>
   <tag></tag>
   <elementGuidId>df8ce918-5412-4ba2-817d-0f938b5a6da9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.link.pts-b-db-14</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[2]/div[2]/p[2]/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>b952e3c0-3673-4145-993e-006e4c5eb489</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>link pts-b-db-14</value>
      <webElementGuid>d2c6be79-42a1-46d2-b828-0fdd93f8d170</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Click Here</value>
      <webElementGuid>cc8b1a41-8d1c-4e39-b7ce-4c59b50f0080</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;yes-card&quot;]/div[@class=&quot;yes-card__body&quot;]/p[@class=&quot;pts-n-db-14 text-center mt-3&quot;]/span[@class=&quot;link pts-b-db-14&quot;]</value>
      <webElementGuid>1248de77-bffc-4c59-ad2b-9bde5f42323f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[2]/div[2]/p[2]/span</value>
      <webElementGuid>97934f95-89cb-4800-9988-094143b8e421</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Select your Television Service Provider'])[1]/following::span[1]</value>
      <webElementGuid>7ed9d8b5-6b34-4dcd-88da-e5548921ea5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='TV'])[1]/following::span[1]</value>
      <webElementGuid>000c084e-f280-48d8-aa3c-a82f82a9a4d4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Click Here']/parent::*</value>
      <webElementGuid>1f980c3e-7c24-4870-80b5-8e52802a4f00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[2]/span</value>
      <webElementGuid>ffa70a14-ee14-4318-94bb-1ee5957e9976</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Click Here' or . = 'Click Here')]</value>
      <webElementGuid>01139ee5-8ed5-4b2f-a16c-7ab4b1ca13b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
