<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Continue with GoogleContinue with Faceb_6932f6</name>
   <tag></tag>
   <elementGuidId>75600084-9fa8-466f-8c57-4d8bf0830c9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.auth__card-body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/div[2]/div[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>870cd5ae-fd5d-451d-ab6e-32c4dc029d71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>auth__card-body</value>
      <webElementGuid>c2f602e2-e919-4aaa-95fc-c405753d50ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In</value>
      <webElementGuid>740f53ee-15d8-45b1-bdba-b806c5615581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[1]/div[@class=&quot;auth__card&quot;]/div[@class=&quot;auth__card-body&quot;]</value>
      <webElementGuid>dc6fd0dd-0ce5-4eb9-8c60-a6bf1044f609</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div[2]/div[2]</value>
      <webElementGuid>6d628f5f-6704-486b-a0e7-6d723f6ec992</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Register'])[1]/following::div[1]</value>
      <webElementGuid>6138a211-6f00-4edf-aa62-7dd343698943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign in'])[1]/following::div[4]</value>
      <webElementGuid>6c2be4a4-64fc-4b73-8bca-fab7edb6ce56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]</value>
      <webElementGuid>32b03899-825c-4ce9-9222-d03f2b618629</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In' or . = 'Continue with GoogleContinue with FacebookContinue with AppleEmail *Password *Forgot Password?Sign In')]</value>
      <webElementGuid>cdfd519a-8aff-4ad9-8ae3-4ffcc6fffe16</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
