<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_On NowSign out</name>
   <tag></tag>
   <elementGuidId>301d4bc1-bf2d-4235-a359-bafbfd4822f3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.watch-header.d-flex.align-items-center.justify-content-between.mb-2</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>2dcf1a16-2e5e-4983-a1d2-8c54fb46467e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>watch-header d-flex align-items-center justify-content-between mb-2</value>
      <webElementGuid>c3955c12-8a83-40f8-b9e2-c914a0f48464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On NowSign out</value>
      <webElementGuid>f7ddfb22-5134-4147-8fb6-b7020b72f4cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;player-container d-flex flex-column&quot;]/div[@class=&quot;watch-header d-flex align-items-center justify-content-between mb-2&quot;]</value>
      <webElementGuid>bff57552-4d46-48aa-a889-7cc257efdb77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div</value>
      <webElementGuid>4667e520-6fe5-4d2a-a140-e0eccf46f303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sorry!'])[1]/preceding::div[2]</value>
      <webElementGuid>529949e1-d723-4f46-b74c-b2ca95bd5d86</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>319e0ada-92a6-4098-b166-d438ddbc9ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'On NowSign out' or . = 'On NowSign out')]</value>
      <webElementGuid>6b221b59-84ea-4d3c-8aa5-c476778edfbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
