<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h3_On Now</name>
   <tag></tag>
   <elementGuidId>bdc9bbc2-895d-4b37-b04c-e6a9f5658768</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>h3.tgd1-b-base-33.float-left</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div[2]/div/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h3</value>
      <webElementGuid>1c82bf94-3f2a-40cc-a5d6-554c97da2c3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tgd1-b-base-33 float-left</value>
      <webElementGuid>48c71bb6-daf3-4029-bab0-486cc6564dd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>On Now</value>
      <webElementGuid>8b08dd78-0d80-46f2-afaf-594c0a6cb59b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;watch-page&quot;]/div[@class=&quot;player-container d-flex flex-column&quot;]/div[@class=&quot;watch-header d-flex align-items-center justify-content-between mb-2&quot;]/h3[@class=&quot;tgd1-b-base-33 float-left&quot;]</value>
      <webElementGuid>c11b6d36-0213-4170-b4ca-b57d40e6db79</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div[2]/div/h3</value>
      <webElementGuid>d0d31e7d-d506-4168-8dd3-0b5d954a30eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Live streaming unavailable'])[1]/preceding::h3[1]</value>
      <webElementGuid>1d33b9ef-a056-4433-af42-4e4c70eed0d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Data available'])[1]/preceding::h3[2]</value>
      <webElementGuid>fbdee064-05e9-47bf-8882-760a38a27686</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='On Now']/parent::*</value>
      <webElementGuid>f9a99b3d-4744-41ce-938b-58efb27f0d31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h3</value>
      <webElementGuid>38372d16-f17e-4a75-9ee7-dba0b04dfba6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h3[(text() = 'On Now' or . = 'On Now')]</value>
      <webElementGuid>6652f226-abc2-40b7-b102-a4b733e070a6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
